{% set version = "0.7.8" %}

package:
  name: drmaa
  version: {{ version }}

source:
  fn: drmaa-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/drmaa/drmaa-{{ version }}.tar.gz
  md5: e3bdd19d7966ea8d33c9e9f36e378edc

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  files:
    - run_test.py
  commands:
    - python run_test.py

about:
  home: https://github.com/pygridtools/drmaa-python
  license: BSD 3-Clause
  summary: Python wrapper around the C DRMAA library.

extra:
  recipe-maintainers:
    - dan-blanchard
    - jakirkham
