# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "QF5DE9Id9lmaU5e24IIOw5rVjEAMc4ANcolQ7jdJpXCnAeUo1PXseU+QSkyaYrKCFIIOnd5q241+0McclDDNw35xwpBeXpRGFZWZAw8gI24E94aHcvoDAde8TgR2M0daqlrUG02gF6wVhyH72Ct8gGW5qdxS1T3ICZsWqVFPT4xsOL1T2iiyTi/fNeHzASMLQimfaudKuslOzZMl7HmIZA0JJAvsKL9FnCZrX+ZmrECk7HylQrSCajI4la4RCfUpemRXwBuj9tCtRW3z0MH0WwEfCje1ioshcx/QLLMI6jgS8DgnSm0FX0nwy4/y6+hpqAtqz72RxabKoCuPIx5vARs7iUXLFCfVpABI90b/uR56Chs+SPQnd/WOBUMLbhgHKzK9HJTSnbt+9Z56BYoI4XUbou02/p9kziyXqXG1Zk2jqJ+v62KTu1lScXIVAJ24eq8XWko/x62+2bMkmKMCmFRuMqsxjU/u9vF21BFTwgzlw52yk4ttMw96HVVIY5haNVShL4ic7Y71JZVOU4z08dIIamucrqoa65qO1q8vRd60faNd4IIEviJV+lB5gWQfooU+K/cdrjWVakq6m672nX64vZD6WtyWWMO0/oillnEHzeN6zQ+NGKr4gUkQWvnOJkTzExAmn1vWQClb+tTNhiU6V0znOWTMsemmFRT/I0k="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
