travis:
  secure:
    BINSTAR_TOKEN: QF5DE9Id9lmaU5e24IIOw5rVjEAMc4ANcolQ7jdJpXCnAeUo1PXseU+QSkyaYrKCFIIOnd5q241+0McclDDNw35xwpBeXpRGFZWZAw8gI24E94aHcvoDAde8TgR2M0daqlrUG02gF6wVhyH72Ct8gGW5qdxS1T3ICZsWqVFPT4xsOL1T2iiyTi/fNeHzASMLQimfaudKuslOzZMl7HmIZA0JJAvsKL9FnCZrX+ZmrECk7HylQrSCajI4la4RCfUpemRXwBuj9tCtRW3z0MH0WwEfCje1ioshcx/QLLMI6jgS8DgnSm0FX0nwy4/y6+hpqAtqz72RxabKoCuPIx5vARs7iUXLFCfVpABI90b/uR56Chs+SPQnd/WOBUMLbhgHKzK9HJTSnbt+9Z56BYoI4XUbou02/p9kziyXqXG1Zk2jqJ+v62KTu1lScXIVAJ24eq8XWko/x62+2bMkmKMCmFRuMqsxjU/u9vF21BFTwgzlw52yk4ttMw96HVVIY5haNVShL4ic7Y71JZVOU4z08dIIamucrqoa65qO1q8vRd60faNd4IIEviJV+lB5gWQfooU+K/cdrjWVakq6m672nX64vZD6WtyWWMO0/oillnEHzeN6zQ+NGKr4gUkQWvnOJkTzExAmn1vWQClb+tTNhiU6V0znOWTMsemmFRT/I0k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
