travis:
  secure:
    BINSTAR_TOKEN: nHCvoDMxYEE/md+/CnQkK/ZKN31MvvRd3lIrfIHcbfFFzpbO0giCZeVp2KXUYCLDK8afYsTqPrbXaAcC/9Nwtx4QqsmevaMuzmNdaf7OOwI5f2qlekfbQF9oSWT3OZJK/JFrnwOoDwSXSPbBpAK6E5So4DLk1AQg0IMGy3ttqdljDmZ/rs6Zx2WdmFkeX7Ycw+ImKFLvNeQtQv3uLjxSRQszs37nLGPMlrOMLS/FsDrBcM4L4u5wvVjUyaxUZHM4+pcnysPMa0YuuLbz9ZpOhhz5qLM1QplSdFLdfCRnKrZPR2l/WozeIklCRNNAQf+CQ96VU3B7Fg74mvUF07OrjHT7g7bk6jliXglt7CmNcKT/+IG8Myjo9VG5QiK0vPHzimbZAL31o+i0BUoXraWBcdt24I0dJEMlyvGGMMv+xESObZda9zAD/fKtC6OIzatlq991ThctgUFZcMoJNQUpg8JOP83si5WpobYL0ELNbSiK5ZoatwYeOqQi2cVXBj4KVhG0gi/SqTL8q47c+i9hZ3QMzn6gCBaExIQ7sKSpNxz0omTFH/tFBIeCC6feYxYWtopHXrImtm4Xo8xSBZ6nykHgbK6qHRNWE4kADZwF4q469G/eKftQ5vlDYRCU7yF+1qZ825XAunT51k2g1vBiUlPuf4xnkKCLRO3xf2GGDWw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
